#Faris alsubaie


#This dataset contains a list of video games with sales greater than 100,000 copies. 
#It was generated by a scrape of vgchartz.com.
library(dplyr)
library(tidyverse)
library(ggplot2)


games <- read.csv("data/vgsales.csv")

#Exploratory Data Analysis

summary(games)
str(games)


NA_S <- games$NA_Sales
EU_S <- games$EU_Sales
JP_S <- games$JP_Sales
Other_S <- games$Other_Sales

sum(NA_S)
, "Microsoft Game Studios", "Sony Computer Entertainment"

games$Publisher %>% 
    ggplot(aes(x = NA_S , y = Publisher))
   
   + 
   geom_histogram() 
  labs(title = "Games Sales")
```
plot(games$Publisher,NA_S)

ggplot(games, aes(NA_S, Publisher)) 
filter(Publisher == "Nintendo")+
  geom_point()



