#Faris alsubaie
# 10/21/2020

#This dataset contains a list of video games with sales greater than 100,000 copies. 
#It was generated by a scrape of vgchartz.com.
# load packages
library(dplyr)
library(ggplot2)
library(tidyverse)

vgsales <- read_csv("data/vgsales.csv")
games <- read.csv("data/vgsales.csv")

#Exploratory Data Analysis
# look at the data
glimpse(games)
summary(games)
str(games)

NA_S <- games$NA_Sales
EU_S <- games$EU_Sales
JP_S <- games$JP_Sales
Other_S <- games$Other_Sales





# Make data tidy, and... take only the 3 major publishers
vgsales_region <- games %>% 
   select(Name, Publisher, ends_with("Sales"), -starts_with("Glo")) %>% 
   pivot_longer(-c(Name, Publisher), names_to = "Region", values_to = "Sales") %>% 
   mutate(Region = str_remove(Region, "_Sales")) %>% 
   filter(Publisher %in% c("Nintendo", "Microsoft Game Studios", "Sony Computer Entertainment"))

unique(vgsales_region$Publisher)

# Compare publisher and sales in different regions:
# aggregrate totals for each publisher (i.e. ignore game titles)
vgsales_region_sum <- vgsales_region %>% 
   group_by(Publisher, Region) %>% 
   summarise(Sales = sum(Sales))

ggplot(vgsales_region_sum, aes(x = Publisher, y = Sales, fill = Region)) +
   geom_col()

#looking at sales for each genre:
ggplot(games, aes(x = Genre, y = Global_Sales, fill = Genre)) +
   geom_col() +
   theme_classic()
   
#looking at sales for each genre and compare sales for each region:
vgsales_genre <- games %>% 
   select(Genre, ends_with("Sales"), -starts_with("Glo")) %>% 
   summarise(Sales = sum(ends_with("Sales")))

ggplot(vgsales_genre) +
   geom_col()


